### PR TITLE
Big Refactort to align with sensu plugin format

### PR DESCRIPTION
**Pull request by warmfusion**
References:
- http://sensu-plugins.io/
- https://github.com/sensu-plugins

### CODE REVIEW

**Comment by warmfusion** [comment]
Hi @countryHick 
Would you be able to have a quick lookover these changes and sanity check them?

No real functionality changes - a curios typo around the snmp trap handling and refactors based on robucop but otherwise its a topological change and some(lots) of additional framework stuff to make the extension more portable

Cheers

**Comment by ghost** [comment]
First glance looks fine - will try and get my testing env back up and running and apply there to check.

**Comment by ghost** [comment]
@warmfusion - finally getting back to this - are you good to merge or have you transferred to the main plugins repos yet?

**Comment by warmfusion** [comment]
Happy to merge away - no one's suggested how to incorporate extensions into the sensu architecture, so might as well follow some conventions like this for now.

**Pull request merged**
